[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[dependencies]
circus = { path = "." }
python = "3.12.*"

[package]
name = "circus"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build-dependencies]
cmake = ">=3.27,<4"

[package.host-dependencies]
python = "3.12.*"
nanobind = "2.8.*"
eigen = ">=3.4.0,<4"
yaml-cpp = ">=0.8.0,<0.9"
nlohmann_json = ">=3.12.0,<4"
pugixml = ">=1.15,<2"
libcurl = ">=8.14.1,<9"
# qt6-main = ">=6.9.2,<7"
libmujoco = ">=3.3.2,<4"

# macOS usa il proprio OpenGL, non serve libgl-devel

[tasks]
test = "python -c 'import circuspy; circuspy.test()'" 

[activation]
env = {DYLD_LIBRARY_PATH = "$DYLD_LIBRARY_PATH:$CONDA_PREFIX/lib",PATH = "$CONDA_PREFIX/bin:$PATH",CMAKE_PREFIX_PATH = "/Users/emanuelerucci/Qt/6.9.2/macos/lib/cmake"}


